### ISSUE TITLE
Error while starting pa11y

### ISSUE THREAD

**Issue by nicodeclercq** [RobLoach/docker-pa11y#6]
I encounter an error at the end of the launching of pa11y using the command indicated on readme:
````sh
docker-compose -f compose/docker-compose.yml up
````
````
database_1  | 2019-02-01T08:49:28.744+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
: not found | /entrypoint.sh: 2: /entrypoint.sh:
: not found | /entrypoint.sh: 5: /entrypoint.sh:   "port": 4000,\n
: not found | /entrypoint.sh: 6: /entrypoint.sh:   "noindex": true,\n
: not found | /entrypoint.sh: 7: /entrypoint.sh:   "readonly": false,\n
: not found | /entrypoint.sh: 8: /entrypoint.sh:   "webservice": {\n
web_1       | {
web_1       |
: not found | /entrypoint.sh: 9: /entrypoint.sh:     "database": "mongodb://mongodb/pa11y-webservice",\n
: not found | /entrypoint.sh: 10: /entrypoint.sh:     "host": "0.0.0.0",\n
: not found | /entrypoint.sh: 11: /entrypoint.sh:     "port": 3000,\n
: not found | /entrypoint.sh: 12: /entrypoint.sh:     "cron": "0 30 0 * * *"\n
: not found | /entrypoint.sh: 13: /entrypoint.sh:   }\n
web_1       | /entrypoint.sh: 14: /entrypoint.sh: }: not found
: not found | /entrypoint.sh: 15: /entrypoint.sh:
web_1       | module.js:341
web_1       |     throw err;
web_1       |     ^
web_1       |
'eb_1       | Error: Cannot find module '/dashboard/.
web_1       |     at Function.Module._resolveFilename (module.js:339:15)
web_1       |     at Function.Module._load (module.js:290:25)
web_1       |     at Function.Module.runMain (module.js:447:10)
web_1       |     at startup (node.js:148:18)
web_1       |     at node.js:405:3
compose_web_1 exited with code 1
````

Is there any configuration I need to had in order to make all work?

**Comment by RobLoach** [comment]
Thanks a lot, this could really do with an update.

**Comment by NickStees** [comment]
I am also getting this error, I tried a few different things and couldn't get it working. I am on Windows BTW
